### ISSUE TITLE
Backend Development | `Create database tables`

### ISSUE THREAD

**Issue by 4D-Coder** [4D-Coder/WanderWattzEMS#11]
- [ ] Write migration scripts for the Users table.
- [ ] Script and run migrations for SolarPanels, Batteries, etc.
- [ ] Test database integrity and relationships.
