### ISSUE TITLE
Backend Development | `Setup the development environment`

### ISSUE THREAD

**Issue by 4D-Coder** [4D-Coder/WanderWattzEMS#12]
- [x] Decide on a backend framework and initialize a project.
- [x] Setup version control (e.g., Git) and create a repository.
- [x] Set up a testing environment and library for the backend.
- [ ] Install and configure a database (e.g., PostgreSQL).
