### ISSUE TITLE
CI/CD Pipeline | `Implement CI solution`

### ISSUE THREAD

**Issue by 4D-Coder** [4D-Coder/WanderWattzEMS#2]
- [ ] Determine CI platform (Github Actions, CircleCI, TravisCI, etc.)
- [ ] Model CI workflow visually in Miro
- [ ] Implement pipeline into project
