### ISSUE TITLE
Backend Development | `Implement APIs for fetching location and weather data`

### ISSUE THREAD

**Issue by 4D-Coder** [4D-Coder/WanderWattzEMS#9]
- [ ] Research and select a weather data, geolocation, and solar panel data API.
- [ ] Design test cases for the solar panel data input API.
- [ ] Write tests for fetching and processing weather data.
- [x] Write tests for fetching and processing location data.
- [ ] Implement API call functions to fetch current and forecasted weather data.

EXTENSION
- [ ] Store and process relevant weather data for optimization recommendations.
